"""Predefined stone catalog for Rated Worktops."""

STONES = [
    {
        "id": "carrara-white",
        "name": "Carrara White Marble",
        "type": "Marble",
        "finish": "Polished",
        "origin": "Tuscany, Italy",
        "description": "Classic soft white marble with feathery grey veining. Timeless and bright.",
        "image_url": "https://images.unsplash.com/photo-1558346648-9757f2fa4474?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#E8E6E1",
    },
    {
        "id": "nero-marquina",
        "name": "Nero Marquina",
        "type": "Marble",
        "finish": "Polished",
        "origin": "Basque Country, Spain",
        "description": "Deep black marble with sharp, bright white veining. Dramatic and luxurious.",
        "image_url": "https://images.unsplash.com/photo-1550053808-52a75a05955d?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#1A1A1C",
    },
    {
        "id": "calacatta-gold",
        "name": "Calacatta Gold",
        "type": "Marble",
        "finish": "Polished",
        "origin": "Carrara, Italy",
        "description": "Bright white field with bold, warm gold veining. Statement-making elegance.",
        "image_url": "https://images.unsplash.com/photo-1615968679312-9b7ed9f04e79?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#F1ECDD",
    },
    {
        "id": "rough-granite",
        "name": "Charcoal Granite",
        "type": "Granite",
        "finish": "Honed",
        "origin": "Brazil",
        "description": "Dense charcoal granite flecked with mica. Highly durable, matte finish.",
        "image_url": "https://images.pexels.com/photos/7683580/pexels-photo-7683580.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "swatch_color": "#2D2D2F",
    },
    {
        "id": "arabescato",
        "name": "Arabescato Vagli",
        "type": "Marble",
        "finish": "Polished",
        "origin": "Apuan Alps, Italy",
        "description": "Cool white background with bold, theatrical grey veining patterns.",
        "image_url": "https://images.unsplash.com/photo-1604147706283-d7119b5b822c?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#EFEEEA",
    },
    {
        "id": "quartz-pearl",
        "name": "Pearl White Quartz",
        "type": "Engineered Quartz",
        "finish": "Polished",
        "origin": "Engineered Stone",
        "description": "Uniform off-white engineered quartz with subtle sparkle. Stain-resistant.",
        "image_url": "https://images.unsplash.com/photo-1615873968403-89e068629265?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#EDEAE2",
    },
    {
        "id": "verde-alpi",
        "name": "Verde Alpi",
        "type": "Marble",
        "finish": "Polished",
        "origin": "Aosta Valley, Italy",
        "description": "Deep forest green marble with intricate white veining. Bold biophilic accent.",
        "image_url": "https://images.unsplash.com/photo-1604147495798-57beb5d6af73?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#1F3A2E",
    },
    {
        "id": "travertine-cream",
        "name": "Cream Travertine",
        "type": "Travertine",
        "finish": "Honed",
        "origin": "Tivoli, Italy",
        "description": "Warm cream travertine with natural pitting. Mediterranean character.",
        "image_url": "https://images.unsplash.com/photo-1615874959474-d609969a20ed?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#D7C8AC",
    },
    {
        "id": "statuario-venato",
        "name": "Statuario Venato",
        "type": "Marble",
        "finish": "Polished",
        "origin": "Carrara, Italy",
        "description": "Brilliant white with sharp linear grey veins. Sculptural and architectural.",
        "image_url": "https://images.unsplash.com/photo-1597484661973-ee6cd0b6482c?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#F4F3EF",
    },
    {
        "id": "concrete-grey",
        "name": "Industrial Concrete",
        "type": "Engineered Quartz",
        "finish": "Suede",
        "origin": "Engineered Stone",
        "description": "Mid-grey concrete-look quartz with subtle texture. Industrial chic.",
        "image_url": "https://images.unsplash.com/photo-1604147495798-57beb5d6af73?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#7A7A7D",
    },
    {
        "id": "taj-mahal",
        "name": "Taj Mahal Quartzite",
        "type": "Quartzite",
        "finish": "Leathered",
        "origin": "Brazil",
        "description": "Warm cream quartzite with golden waves. Tough as granite, soft as marble.",
        "image_url": "https://images.unsplash.com/photo-1604147706283-d7119b5b822c?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#E2D5B5",
    },
    {
        "id": "blue-bahia",
        "name": "Blue Bahia Granite",
        "type": "Granite",
        "finish": "Polished",
        "origin": "Bahia, Brazil",
        "description": "Rare cobalt blue granite with crystalline structure. Premium statement stone.",
        "image_url": "https://images.unsplash.com/photo-1597484661973-ee6cd0b6482c?crop=entropy&cs=srgb&fm=jpg&q=85&w=900",
        "swatch_color": "#1E3A5F",
    },
]


def get_stone_by_id(stone_id: str):
    for s in STONES:
        if s["id"] == stone_id:
            return s
    return None
